# Generated by Django 5.0.3 on 2024-10-11 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('status', models.CharField(max_length=255, verbose_name='Статус')),
                ('lat_a', models.CharField(max_length=255, verbose_name='Широта А')),
                ('lon_a', models.CharField(max_length=255, verbose_name='Долгота А')),
                ('lat_b', models.CharField(blank=True, max_length=255, null=True, verbose_name='Широта Б')),
                ('lon_b', models.CharField(blank=True, max_length=255, null=True, verbose_name='Долгота Б')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_visit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Поcещаемость',
            },
        ),
    ]
