# Generated by Django 5.0.3 on 2024-10-11 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_visit_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(verbose_name='Зарплата')),
                ('type', models.CharField(choices=[('1', 'Зарплата'), ('2', 'Аванс')], max_length=255, verbose_name='Вид зарплаты')),
                ('date', models.DateField(verbose_name='Когда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Зарплата',
            },
        ),
    ]
