# Generated by Django 5.0.3 on 2024-10-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='summ',
            field=models.IntegerField(default=1, verbose_name='Общая сумма зарплаты'),
            preserve_default=False,
        ),
    ]
