# Generated by Django 5.0.3 on 2024-10-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_salary_summ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='summ',
        ),
    ]
