# Generated by Django 5.0.3 on 2024-10-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_logo_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
