# Generated by Django 5.0.3 on 2024-10-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('1', 'Зарплата'), ('2', 'Аванс')], default=1, max_length=255, verbose_name='Вид зарплаты'),
            preserve_default=False,
        ),
    ]
