# Generated by Django 5.0.3 on 2024-10-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_salary_remove_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='summ',
            field=models.IntegerField(default=1, verbose_name='Общая сумма зарплаты'),
            preserve_default=False,
        ),
    ]
